<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#The-Numpy-ndarray:-A-Multidimesional-Array-Object" data-toc-modified-id="The-Numpy-ndarray:-A-Multidimesional-Array-Object-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>The Numpy ndarray: A Multidimesional Array Object</a></span><ul class="toc-item"><li><span><a href="#Creating-ndarrays" data-toc-modified-id="Creating-ndarrays-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Creating ndarrays</a></span></li><li><span><a href="#Data-Types-for-ndarrays" data-toc-modified-id="Data-Types-for-ndarrays-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Data Types for ndarrays</a></span></li><li><span><a href="#Arithmetic-with-Numpy-Arrays" data-toc-modified-id="Arithmetic-with-Numpy-Arrays-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Arithmetic with Numpy Arrays</a></span></li><li><span><a href="#Basic-Indexing-and-Slicing" data-toc-modified-id="Basic-Indexing-and-Slicing-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Basic Indexing and Slicing</a></span><ul class="toc-item"><li><span><a href="#Indexing-with-slices" data-toc-modified-id="Indexing-with-slices-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>Indexing with slices</a></span></li></ul></li><li><span><a href="#Boolean-Indexing" data-toc-modified-id="Boolean-Indexing-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Boolean Indexing</a></span></li><li><span><a href="#Fancy-Indexing" data-toc-modified-id="Fancy-Indexing-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Fancy Indexing</a></span></li><li><span><a href="#Transposing-Arays-and-Swapping-Axes" data-toc-modified-id="Transposing-Arays-and-Swapping-Axes-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Transposing Arays and Swapping Axes</a></span></li></ul></li></ul></div>

In [4]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%timeit for _ in range(10): my_arr2 = my_arr * 2

21.9 ms ± 251 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
%timeit for _ in range(10): my_list2 = [x*2 for x in my_list]

907 ms ± 10.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# The Numpy ndarray: A Multidimesional Array Object

In [6]:
import numpy as np
data = np.random.randn(2, 3)
data

array([[ 0.02325098, -0.43251407,  0.1863689 ],
       [ 0.36754831,  0.72814399, -0.27099182]])

In [7]:
data * 10

array([[ 0.23250982, -4.32514074,  1.86368899],
       [ 3.67548311,  7.28143992, -2.70991819]])

In [8]:
data + data

array([[ 0.04650196, -0.86502815,  0.3727378 ],
       [ 0.73509662,  1.45628798, -0.54198364]])

## Creating ndarrays

In [15]:
data1 = [6, 7.5, 8, 0, 1]
%timeit arr1 = np.array(data1)
data2 = [6.0, 7.5, 8.0, 0.0, 1.0]
%timeit arr2 = np.array(data2)
arr1.dtype

999 ns ± 5.06 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
785 ns ± 7.31 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


dtype('float64')

In [23]:
data2 = [[1, 2, "3", 4],[5,6,7,8], [2,5,8,6]]
arr2 = np.array(data2)
print(arr2.ndim, arr2.shape)
arr2

2 (3, 4)


array([['1', '2', '3', '4'],
       ['5', '6', '7', '8'],
       ['2', '5', '8', '6']], dtype='<U11')

In [30]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [36]:
%timeit np.empty((100,100))
%timeit np.zeros((100,100))
# Empty is more faster

491 ns ± 5.95 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
2.95 µs ± 51.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [40]:
%timeit range(100)
%timeit np.arange(100)
# 如果用于循环， range效率更高

215 ns ± 2.55 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
661 ns ± 5.73 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Data Types for ndarrays

In [45]:
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr2 = np.array([1, 2, 3], dtype = np.int32)
print(arr1.dtype, arr2.dtype)

float64 int32


In [49]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_arr = arr.astype(np.float32)
float_arr

array([1., 2., 3., 4., 5.], dtype=float32)

## Arithmetic with Numpy Arrays

In [56]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr * arr)
print(arr - arr)
%timeit 1/arr
%timeit 1./arr

[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
1.14 µs ± 10.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
831 ns ± 6.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [57]:
arr ** 5

array([[1.000e+00, 3.200e+01, 2.430e+02],
       [1.024e+03, 3.125e+03, 7.776e+03]])

In [62]:
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing

In [66]:
arr = np.arange(10)
print("arr", arr)
arr[2:6] = 102
print("arr", arr)

arr [0 1 2 3 4 5 6 7 8 9]
arr [  0   1 102 102 102 102   6   7   8   9]


In [70]:
arr_slice = arr[5:8]
arr_slice[1] = 2

array([  0,   1, 102, 102, 102, 102,  25,   7,   8,   9])

In [71]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [75]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [78]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### Indexing with slices

In [80]:
arr = np.array([0, 1, 2, 3, 4, 64, 64, 64, 8, 9])
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [90]:
arr2d = np.array([[1,2,3], [3,4,5], [6,7,8], [9,10,11]])
arr2d

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [96]:
arr2d[3:, :]

array([[ 9, 10, 11]])

In [107]:
x = np.array([1, 2])
x.T

array([1, 2])

## Boolean Indexing

In [136]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 1.614442    1.13947949  0.68326433 -2.55914869]
 [-0.4807243  -0.29288407 -0.6061266   0.56134764]
 [ 0.7457706  -0.67538601 -0.72560915  0.44244156]
 [ 0.89939637 -0.21818426 -0.89141747 -0.3439064 ]
 [ 0.55551838 -1.82490214  0.94666401 -0.2004022 ]
 [-3.24289153 -0.96683512 -1.24123062  2.40016807]
 [-0.21289151 -0.29819749 -0.53063639  0.00528255]]


In [137]:
data[names == 'Bob']

array([[ 1.614442  ,  1.13947949,  0.68326433, -2.55914869],
       [ 0.89939637, -0.21818426, -0.89141747, -0.3439064 ]])

In [138]:
data[names == 'Bob', 1:]

array([[ 1.13947949,  0.68326433, -2.55914869],
       [-0.21818426, -0.89141747, -0.3439064 ]])

In [139]:
data[names != 'Bob']

array([[-0.4807243 , -0.29288407, -0.6061266 ,  0.56134764],
       [ 0.7457706 , -0.67538601, -0.72560915,  0.44244156],
       [ 0.55551838, -1.82490214,  0.94666401, -0.2004022 ],
       [-3.24289153, -0.96683512, -1.24123062,  2.40016807],
       [-0.21289151, -0.29819749, -0.53063639,  0.00528255]])

In [141]:
mask = (names == 'Bob') | (names == 'Will')
data[mask]

array([[ 1.614442  ,  1.13947949,  0.68326433, -2.55914869],
       [ 0.7457706 , -0.67538601, -0.72560915,  0.44244156],
       [ 0.89939637, -0.21818426, -0.89141747, -0.3439064 ],
       [ 0.55551838, -1.82490214,  0.94666401, -0.2004022 ]])

## Fancy Indexing

In [156]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [157]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [161]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [163]:
arr[[1, 5, 7, 2]][:, [0,2,1,2]]

array([[ 4,  6,  5,  6],
       [20, 22, 21, 22],
       [28, 30, 29, 30],
       [ 8, 10,  9, 10]])

In [149]:
arr = np.arange(125).reshape((5,5,5))
arr

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]]])

In [152]:
arr[[1, 4, 2, 3], [0, 3, 1, 2]]

array([[ 25,  26,  27,  28,  29],
       [115, 116, 117, 118, 119],
       [ 55,  56,  57,  58,  59],
       [ 85,  86,  87,  88,  89]])

In [154]:
arr[4,3]

array([115, 116, 117, 118, 119])

## Transposing Arays and Swapping Axes

In [165]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [168]:
arr2 = arr.T
arr2[:, 1] = 125
arr2
arr

array([[  0,   1,   2,   3,   4],
       [125, 125, 125, 125, 125],
       [ 10,  11,  12,  13,  14]])

SyntaxError: invalid syntax (<ipython-input-169-40896abc50c0>, line 1)