<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction-to-pandas-Data-Structures" data-toc-modified-id="Introduction-to-pandas-Data-Structures-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction to pandas Data Structures</a></span><ul class="toc-item"><li><span><a href="#Series" data-toc-modified-id="Series-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Series</a></span></li><li><span><a href="#DataFrame" data-toc-modified-id="DataFrame-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>DataFrame</a></span></li><li><span><a href="#Index-Objects" data-toc-modified-id="Index-Objects-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Index Objects</a></span></li></ul></li><li><span><a href="#Essential-Functionality" data-toc-modified-id="Essential-Functionality-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Essential Functionality</a></span><ul class="toc-item"><li><span><a href="#Reindexing" data-toc-modified-id="Reindexing-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Reindexing</a></span></li><li><span><a href="#Arithmetic-and-Data-Alignment" data-toc-modified-id="Arithmetic-and-Data-Alignment-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Arithmetic and Data Alignment</a></span><ul class="toc-item"><li><span><a href="#Arithmetic-methods-with-fill-values" data-toc-modified-id="Arithmetic-methods-with-fill-values-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>Arithmetic methods with fill values</a></span></li><li><span><a href="#Operations-between-DataFrame-and-Series" data-toc-modified-id="Operations-between-DataFrame-and-Series-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>Operations between DataFrame and Series</a></span></li></ul></li><li><span><a href="#Function-Application-and-Mappinp" data-toc-modified-id="Function-Application-and-Mappinp-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Function Application and Mappinp</a></span></li><li><span><a href="#Sorting-and-Ranking" data-toc-modified-id="Sorting-and-Ranking-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Sorting and Ranking</a></span></li><li><span><a href="#Axis-Indexes-with-Duplicate-Lables" data-toc-modified-id="Axis-Indexes-with-Duplicate-Lables-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Axis Indexes with Duplicate Lables</a></span></li></ul></li><li><span><a href="#Summarizing-and-Computing-Descriptive-Statistics" data-toc-modified-id="Summarizing-and-Computing-Descriptive-Statistics-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Summarizing and Computing Descriptive Statistics</a></span><ul class="toc-item"><li><span><a href="#Correlation-and-Covariance" data-toc-modified-id="Correlation-and-Covariance-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Correlation and Covariance</a></span></li><li><span><a href="#Unique-Values,-Value-Counts,-and-Membership" data-toc-modified-id="Unique-Values,-Value-Counts,-and-Membership-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Unique Values, Value Counts, and Membership</a></span></li></ul></li></ul></div>

In [3]:
import pandas as pd

# Introduction to pandas Data Structures

## Series

In [4]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
print(obj.values)
print(obj.index)

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


In [6]:
obj2 = pd.Series([4, 7, -5, 3], index=['a', 'b', 'c', 'd'])
obj2

a    4
b    7
c   -5
d    3
dtype: int64

In [7]:
print(obj2.values)
print(obj2.index)

[ 4  7 -5  3]
Index(['a', 'b', 'c', 'd'], dtype='object')


In [8]:
obj2[obj2>10]
print(obj2*2)
print(np.exp(obj2))

a     8
b    14
c   -10
d     6
dtype: int64
a      54.598150
b    1096.633158
c       0.006738
d      20.085537
dtype: float64


In [9]:
'b' in obj2

True

In [10]:
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [11]:
states = ['Calfornia', 'Ohio', 'Oregon', 'Texas']
obj3 = pd.Series(sdata, index=states)
pd.isnull(obj3)

Calfornia     True
Ohio         False
Oregon       False
Texas        False
dtype: bool

In [12]:
obj3.name = 'population'
obj3.index.name='state'
obj3

state
Calfornia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
Name: population, dtype: float64

In [13]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## DataFrame

In [14]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year':[2000, 2001, 2002, 2001, 2002, 2003],
       'pop': [1.7, 1.7, 3.6, 2.4, 2.9 ,3.2]}
frame = pd.DataFrame(data)
frame.head()

pop   state  year
0  1.7    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [15]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.7
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [16]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.7  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [17]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [18]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [19]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [20]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.7  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [21]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.7   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [22]:
val = pd.Series([-1.2, -1.5, -1.7, -2.5], index = ['two', 'three', 'five', 'eleven'])
frame2['debet'] = val
frame2

year   state  pop  debt  debet
one    2000    Ohio  1.7   0.0    NaN
two    2001    Ohio  1.7   1.0   -1.2
three  2002    Ohio  3.6   2.0   -1.5
four   2001  Nevada  2.4   3.0    NaN
five   2002  Nevada  2.9   4.0   -1.7
six    2003  Nevada  3.2   5.0    NaN

In [23]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  debet  eastern
one    2000    Ohio  1.7   0.0    NaN     True
two    2001    Ohio  1.7   1.0   -1.2     True
three  2002    Ohio  3.6   2.0   -1.5     True
four   2001  Nevada  2.4   3.0    NaN    False
five   2002  Nevada  2.9   4.0   -1.7    False
six    2003  Nevada  3.2   5.0    NaN    False

In [24]:
del frame2['eastern']
frame2

year   state  pop  debt  debet
one    2000    Ohio  1.7   0.0    NaN
two    2001    Ohio  1.7   1.0   -1.2
three  2002    Ohio  3.6   2.0   -1.5
four   2001  Nevada  2.4   3.0    NaN
five   2002  Nevada  2.9   4.0   -1.7
six    2003  Nevada  3.2   5.0    NaN

In [25]:
pop = {'Nevada' : {2001:2.4, 2002:2.9}, 
      'Ohio': {2000:1.5, 2001:1.7, 2002:3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [26]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [27]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [28]:
type(frame3.values)

numpy.ndarray

In [29]:
frame2.values

array([[2000, 'Ohio', 1.7, 0.0, nan],
       [2001, 'Ohio', 1.7, 1.0, -1.2],
       [2002, 'Ohio', 3.6, 2.0, -1.5],
       [2001, 'Nevada', 2.4, 3.0, nan],
       [2002, 'Nevada', 2.9, 4.0, -1.7],
       [2003, 'Nevada', 3.2, 5.0, nan]], dtype=object)

## Index Objects

In [30]:
obj = pd.Series(range(3), index = ['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [31]:
index[1:]

Index(['b', 'c'], dtype='object')

In [32]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [33]:
obj2 = pd.Series([1.5, -2.5, 0], index = labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [34]:
obj2.index is labels
obj.index = labels

In [35]:
obj

0    0
1    1
2    2
dtype: int64

In [36]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [37]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [38]:
'Ohio' in frame3.columns

True

In [39]:
2003 in frame3.index

False

In [40]:
dup_labels = pd.Index(['foo', 'foo', 'bar'])

In [41]:
frame3.index = dup_labels

In [42]:
frame3

state  Nevada  Ohio
foo       NaN   1.5
foo       2.4   1.7
bar       2.9   3.6

# Essential Functionality

## Reindexing

## Arithmetic and Data Alignment

In [43]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index = ['a', 'c', 'd', 'e'])

In [44]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a', 'c', 'e', 'f', 'g'])

In [45]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [46]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [47]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [50]:
df1 = pd.DataFrame(np.arange(9).reshape(3, 3), columns = list('bcd'),
                                       index = ['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape(4,3), columns=list('bde'),
                  index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [51]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [52]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [54]:
df1 = pd.DataFrame({'A':[1,2]})
df2 = pd.DataFrame({'B':[3,4]})
df1

A
0  1
1  2

In [55]:
df2

B
0  3
1  4

In [56]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

### Arithmetic methods with fill values

In [58]:
df1 = pd.DataFrame(np.arange(12.).reshape(3,4), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape(4,5), columns=list('abcde'))
df2.loc[1, 'b']= np.nan
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [59]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [60]:
df1 - df2

a    b    c    d   e
0  0.0  0.0  0.0  0.0 NaN
1 -1.0  NaN -1.0 -1.0 NaN
2 -2.0 -2.0 -2.0 -2.0 NaN
3  NaN  NaN  NaN  NaN NaN

In [64]:
df1.rsub(df2, fill_value=0)

a     b     c     d     e
0   0.0   0.0   0.0   0.0   4.0
1   1.0  -5.0   1.0   1.0   9.0
2   2.0   2.0   2.0   2.0  14.0
3  15.0  16.0  17.0  18.0  19.0

### Operations between DataFrame and Series

In [89]:
frame = pd.DataFrame(np.arange(12.).reshape(4,3), columns=list('bce')
                  ,index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
frame

b     c     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [91]:
frame.iloc[:,0]

Utah      0.0
Ohio      3.0
Texas     6.0
Oregon    9.0
Name: b, dtype: float64

In [95]:
frame.sub(frame.iloc[:,0], axis='index')

b    c    e
Utah    0.0  1.0  2.0
Ohio    0.0  1.0  2.0
Texas   0.0  1.0  2.0
Oregon  0.0  1.0  2.0

In [69]:
series

pop       1.7
state    Ohio
year     2000
Name: 0, dtype: object

## Function Application and Mappinp

In [97]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [98]:
frame

b         d         e
Utah   -0.781577  0.034397 -0.884018
Ohio   -0.083825 -1.035248  1.109388
Texas   0.399227  1.971154  1.909513
Oregon -0.778201  1.316708 -1.213957

In [99]:
np.abs(frame)

b         d         e
Utah    0.781577  0.034397  0.884018
Ohio    0.083825  1.035248  1.109388
Texas   0.399227  1.971154  1.909513
Oregon  0.778201  1.316708  1.213957

In [101]:
frame.max(axis)

b    0.399227
d    1.971154
e    1.909513
dtype: float64

In [102]:
f = lambda x: x.max() - x.min()

In [104]:
frame.apply(f, axis='columns')

Utah      0.918414
Ohio      2.144636
Texas     1.571928
Oregon    2.530665
dtype: float64

In [108]:
def f(x):
    return pd.Series([x.min(), x.max()], index = ['min', 'max'])
frame.apply(f, axis='columns')

min       max
Utah   -0.884018  0.034397
Ohio   -1.035248  1.109388
Texas   0.399227  1.971154
Oregon -1.213957  1.316708

In [117]:
format  = lambda x:'%.2f' % x
frame.applymap(format)

b      d      e
Utah    -0.78   0.03  -0.88
Ohio    -0.08  -1.04   1.11
Texas    0.40   1.97   1.91
Oregon  -0.78   1.32  -1.21

In [110]:
'%.2f' %6

'6.00'

## Sorting and Ranking

In [122]:
frame = pd.DataFrame(np.arange(8).reshape(2,4),
                    index = ['three', 'one'],
                    columns = list('dabc'))
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [123]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [126]:
frame.sort_index(axis='columns')

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [133]:
frame = pd.DataFrame({'b':[4,7,-3,-3], 'a':[0, 1, 1, 0]})
frame

a  b
0  0  4
1  1  7
2  1 -3
3  0 -3

In [135]:
frame.sort_values(by=['b', 'a'])

a  b
3  0 -3
2  1 -3
0  0  4
1  1  7

In [137]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [139]:
obj.rank(method='max')

0    7.0
1    1.0
2    7.0
3    5.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [141]:
frame = pd.DataFrame({'b':[4.3, 7, -3, 2], 'a':[0,1,0,1], 'c':[-2,5,8,-2.5]})
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [148]:
frame.rank(method='dense')

a    b    c
0  1.0  3.0  2.0
1  2.0  4.0  3.0
2  1.0  1.0  4.0
3  2.0  2.0  1.0

## Axis Indexes with Duplicate Lables

In [149]:
obj = pd.Series(range(5), index =['a', 'a', 'b', 'b', 'c'])

In [154]:
obj.index.is_unique

False

In [155]:
obj['a']

a    0
a    1
dtype: int64

In [157]:
obj.loc['b']

b    2
b    3
dtype: int64

# Summarizing and Computing Descriptive Statistics

In [162]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan],[0.75, -1.3] ],
                 index=['a','b','c','d'],
                 columns=['a', 'b'])
df

a    b
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [164]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [166]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [171]:
df.idxmax(axis=1)

a      a
b      a
c    NaN
d      a
dtype: object

In [172]:
df.cumsum()

a    b
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [173]:
df.describe()

a         b
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

## Correlation and Covariance

In [175]:
df = pd.DataFrame(np.random.randn(4,4), index=list('abcd'), columns=list('defg'))

In [176]:
df

d         e         f         g
a  0.109428 -0.115025  0.317590  1.867478
b -1.204576 -0.801202  0.168410 -0.463844
c -0.221460 -0.924729  0.265556  1.821467
d -0.814534 -1.274787 -0.922346 -1.164410

In [180]:
df.pct_change().corr()

d         e         f         g
d  1.000000 -0.965400 -0.527568 -0.380875
e -0.965400  1.000000  0.287782  0.608816
f -0.527568  0.287782  1.000000 -0.584545
g -0.380875  0.608816 -0.584545  1.000000

In [181]:
df.pct_change().cov()

d          e          f         g
d  58.857181 -24.384096 -10.788125 -5.903705
e -24.384096  10.839262   2.525407  4.049755
f -10.788125   2.525407   7.104528 -3.147952
g  -5.903705   4.049755  -3.147952  4.082119

## Unique Values, Value Counts, and Membership

In [183]:
obj=pd.Series(list('aabbffbbaecc'))
obj.unique()

array(['a', 'b', 'f', 'e', 'c'], dtype=object)

In [189]:
%timeit obj.value_counts()
%timeit obj.value_counts( sort=False)

437 µs ± 26.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
192 µs ± 932 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [192]:
mask = obj.isin(['b', 'c'])
mask

0     False
1     False
2      True
3      True
4     False
5     False
6      True
7      True
8     False
9     False
10     True
11     True
dtype: bool

In [193]:
obj[mask]

2     b
3     b
6     b
7     b
10    c
11    c
dtype: object

In [195]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])

In [197]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [220]:
data = pd.DataFrame(np.random.randint(1,4,size=(4,4)), columns=['Qu1','Qu2','Qu3','Qu4'], index=list('abcd'))
data

Qu1  Qu2  Qu3  Qu4
a    2    3    1    2
b    3    2    1    2
c    2    1    2    3
d    1    2    1    2

In [221]:
data.apply(pd.value_counts, axis=1)

1    2    3
a  1.0  2.0  1.0
b  1.0  2.0  1.0
c  1.0  2.0  1.0
d  2.0  2.0  NaN